config/routes.rb
Rails.application.routes.draw do
  resources :authors
  get 'pages/info'
  root to: redirect('/ideas')
  resources :ideas
  # match 'ideas/:id/approve', to: 'ideas#approve', :as => :approve_idea, :via => :post
  get 'ideas/:id/change-status', to: 'ideas#changeStatus', :as => :change_status
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
    mount_uploader :picture, PictureUploader
    enum status: [:Needs_Approval, :Approved] 
    belongs_to :author
    #enum status: { active: 1, inactive: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :email)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy, :approve, :unapprove, :changeStatus]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def changeStatus
    respond_to do |format|
      if @idea.status == 'Needs_Approval'
        if @idea.update(status: 1)
          format.html { redirect_to ideas_url, notice: 'Idea was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { render json: @idea.errors, status: :unprocessable_entity }
        end
      else
        if @idea.update(status: 0)
          format.html { redirect_to ideas_url, notice: 'Idea was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { render json: @idea.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <b><%= form.label :name, :class => "form-label" %></b>
    <%= form.text_field :name, :type => "text", :class => "form-control" %>
  </div>

  <div class="field mb-3">
    <b><%= form.label :description, :class => "form-label" %></b>
    <%= form.text_area :description, :type => "textarea", :class => "form-control"  %>
  </div>

  <div class="field mb-3">
    <b><%= form.label :picture, :class => "form-label"%></b>
    <%= form.file_field :picture, :class => "btn btn-light"   %>
  </div>

  <div class="field mb-3">
    <b><%= form.label :author, :class => "form-label" %></b>
    <%= form.select :author, Author.all.map(&:name), :type => "textarea", :class => "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="title">
  <h1>Ideas</h1>
</div>
<div class="new-idea-button">
  <%= link_to 'New Idea', new_idea_path, :class => "btn btn-primary" %>
</div>
<div class="idea-table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Picture</th>
        <th>Created by</th>
        <th>Status</th>
        <th colspan="4">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @ideas.each do |idea| %>
        <tr>
          <td><%= idea.name %></td>
          <td><%= idea.description %></td>
          <td><%= image_tag idea.picture_url, width: '20%' if idea.picture.present? %></td>
          <td><%= idea.author.email %></td>
          <td><%= idea.status.humanize %></td>
          <td><%= link_to 'Show', idea, class: "btn btn-primary"  %></td>
          <td><%= link_to 'Edit', edit_idea_path(idea), :class => "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
          <% if idea.status.humanize == 'Approved' %>
          <td><%= link_to 'Unapprove', change_status_path(idea), :class => "btn btn-primary" %></td>
          <%else %>
          <td><%= link_to 'Approve', change_status_path(idea), :class => "btn btn-primary" %></td>
         <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path, :class => "btn btn-secondary"   %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tr>
    <th><strong>Name:</strong></th>
    <td> <%= @idea.name %></td>
  </tr>
  <tr>
    <th><strong>Description:</strong></th>
    <td><%= @idea.description %></td>
  </tr>
  <tr>
    <th><strong>Picture:</strong></th>
    <td><%= image_tag(@idea.picture_url, width: 500) if @idea.picture.present? %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_idea_path(@idea), :class => "btn btn-primary"  %>
<%= link_to 'Back', ideas_path, :class => "btn btn-secondary"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">The Idea App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if params[:selected] == 'ideas' %>">
          <a class="nav-link" href="/ideas?selected=ideas">Ideas</a>
        </li>
        <li class="nav-item <%= 'active' if params[:selected] == 'info' %>">
          <a class="nav-link" href="/pages/info?selected=info">Info</a>
        </li>
        <li class="nav-item <%= 'active' if params[:selected] == 'authors' %>">
          <a class="nav-link" href="/authors?selected=authors">Author</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        Rails Girls <%= Time.now.year %>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Hello, Folks!</h1>
<p> Welcome to my first Ruby project ever!</p>
<p> With <3, Gemma</p>